name: todo with websockets

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*"]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ "16.x" ]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2

    - name: Lint
      run: |
        npm run lint

    - name: Build
      run: |
       npm install
