name: todo with websockets

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ "18.x" ]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4

    - name: Build
      run: |
        npm install

    - name: Lint
      run: |
        npm run lint
