name: todo with websockets

on: 
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Tests
      run: npm run test
